import { motion } from "framer-motion";
import {
  Sparkles,
  Wallet,
  Users,
  Map,
  CalendarRange,
  Backpack,
  CloudSun,
  Trophy,
} from "lucide-react";

const features = [
  {
    icon: Sparkles,
    title: "AI Travel Assistant",
    desc: "Auto-generate optimized itineraries, hidden gems, and routes tailored to your mood.",
  },
  {
    icon: Wallet,
    title: "Smart Budget Optimizer",
    desc: "Predict overspending, get cheaper alternatives, and stay on track with live alerts.",
  },
  {
    icon: Users,
    title: "Live Collaboration",
    desc: "Co-edit trips with friends and family in real time — no more group-chat chaos.",
  },
  {
    icon: Map,
    title: "Visual Route Map",
    desc: "An interactive animated world map that turns your itinerary into a story.",
  },
  {
    icon: CalendarRange,
    title: "Timeline & Calendar",
    desc: "Switch between drag-and-drop timeline and elegant calendar views in one click.",
  },
  {
    icon: Backpack,
    title: "Smart Packing Lists",
    desc: "Auto-generated by destination, season, weather, and trip duration.",
  },
  {
    icon: CloudSun,
    title: "Weather-Aware Planning",
    desc: "Best travel dates and day-by-day suggestions based on real forecasts.",
  },
  {
    icon: Trophy,
    title: "Travel Rewards",
    desc: "Earn badges, unlock cities, and turn every trip into an adventure log.",
  },
];

export function Features() {
  return (
    <section id="features" className="relative py-32">
      <div className="container mx-auto px-6">
        <div className="max-w-2xl mb-16">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.6 }}
            className="inline-block px-3 py-1 rounded-full glass text-xs font-medium text-accent mb-5"
          >
            Everything you need
          </motion.div>
          <motion.h2
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.7, delay: 0.05 }}
            className="text-balance text-4xl md:text-5xl font-semibold tracking-tight leading-tight mb-4"
          >
            A travel workspace that actually{" "}
            <span className="gradient-text">thinks ahead.</span>
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.7, delay: 0.1 }}
            className="text-lg text-muted-foreground"
          >
            Eight powerful modules, one beautifully unified experience.
          </motion.p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-80px" }}
              transition={{
                duration: 0.6,
                delay: (i % 4) * 0.08,
                ease: [0.22, 1, 0.36, 1],
              }}
              whileHover={{ y: -4 }}
              className="group glass rounded-2xl p-6 hover:border-white/20 transition-colors relative overflow-hidden"
            >
              <div
                className="absolute -top-20 -right-20 w-40 h-40 rounded-full opacity-0 group-hover:opacity-30 blur-3xl transition-opacity"
                style={{ background: "var(--gradient-primary)" }}
              />
              <div className="relative">
                <div className="w-11 h-11 rounded-xl glass-strong flex items-center justify-center mb-5 group-hover:scale-110 transition-transform">
                  <f.icon className="w-5 h-5 text-accent" strokeWidth={2} />
                </div>
                <h3 className="font-semibold text-base mb-1.5 tracking-tight">
                  {f.title}
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {f.desc}
                </p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
